### ISSUE TITLE
Error when `import tree`

### ISSUE THREAD

**Issue by acxz** [deepmind/tree#82]
```
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/tree/__init__.py", line 23, in <module>
    from .sequence import _is_attrs
  File "/usr/lib/python3.10/site-packages/tree/sequence.py", line 19, in <module>
    from tree import _tree
ImportError: /usr/lib/python3.10/site-packages/tree/_tree.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN4absl12lts_2021032420raw_logging_internal6RawLogENS0_11LogSeverityEPKciS4_z
```

**Comment by ngam** [comment]
How did you get / build this dm-tree tho?

**Comment by acxz** [comment]
Built from source, at git head:
```
python setup.py build
python setup.py install --optimize=1
```

**Comment by acxz** [comment]
I'm sorry which line do I change?

**Comment by ngam** [comment]
Let me first test it. I am building this for conda-forge: https://github.com/conda-forge/dm-tree-feedstock/pull/28



> I'm sorry which line do I change?

```diff
--- a/tree/tree/CMakeLists.txt
+++ b/tree/tree/CMakeLists.txt
@@ -54,1 +54,1 @@ set(PYBIND_VER
-set(PYBIND_VER v2.6.2)
+set(PYBIND_VER v2.9.2)
@@ -71,1 +71,1 @@ set(ABSEIL_VER
-set(ABSEIL_VER 20210324.2)
+set(ABSEIL_VER 20211102.0)
```

**Comment by mweinelt** [comment]
We're seeing the same failure on NixOS with
- python 3.9.12 & 3.10.4
- pybind 2.9.1 & 2.9.2
- absl-cpp 20210324.2 & 20211102.0

**Comment by mweinelt** [comment]
I bisected this issue to our gcc bump from 10 to 11.

**Comment by ccoulombe** [comment]
As of today, this is still an issue when building from source. 
Tried different version of abseil without luck.

@ngam Can you point me to the exact requirements that were used to build v0.1.7 ? (As using https://github.com/deepmind/tree/blob/2cb667a2cd5cd57beacb1e4f3296fa71e282bbea/tree/CMakeLists.txt#L71 does not work correctly.)

**Comment by npanpaliya** [comment]
Please see my comment https://github.com/deepmind/tree/issues/103#issuecomment-1618283988 . With this patch, I was able to compile dm-tree 0.1.8.

**Comment by voidIess** [comment]
I also have this error.

```
$ pip install dm-tree
Requirement already satisfied: dm-tree in ./venv/lib/python3.9/site-packages (0.1.8)

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
(venv) -----------------------------------------------------------------------
$python
Python 3.9.6 (default, Feb  3 2024, 15:58:27)
[Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tree'
```
