### ISSUE TITLE
Add aarch64 support

### ISSUE THREAD

**Issue by seydang** [deepmind/tree#96]
System specs:
![image](https://user-images.githubusercontent.com/53308177/206887927-0fdca3bc-4420-415e-bc07-d53d70dfdf4e.png)

When I try to install the package to my aarch64 Linux/GNU device, i get the following error:

mendel@green-bunny:~$ pip install dm-tree
Collecting dm-tree
  Downloading dm-tree-0.1.7.tar.gz (35 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dm-tree
  Building wheel for dm-tree (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-3.7
      creating build/lib.linux-aarch64-3.7/tree
      copying tree/tree_benchmark.py -> build/lib.linux-aarch64-3.7/tree
      copying tree/tree_test.py -> build/lib.linux-aarch64-3.7/tree
      copying tree/sequence.py -> build/lib.linux-aarch64-3.7/tree
      copying tree/__init__.py -> build/lib.linux-aarch64-3.7/tree
      running build_ext
      Traceback (most recent call last):
        File "/tmp/pip-install-kddajcat/dm-tree_b4c24d53c3804d088de23bf53e53c2cb/setup.py", line 77, in _check_build_environment
          subprocess.check_call(['cmake', '--version'])
        File "/usr/lib/python3.7/subprocess.py", line 342, in check_call
          retcode = call(*popenargs, **kwargs)
        File "/usr/lib/python3.7/subprocess.py", line 323, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
          restore_signals, start_new_session)
        File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-kddajcat/dm-tree_b4c24d53c3804d088de23bf53e53c2cb/setup.py", line 155, in <module>
          keywords='tree nest flatten',
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 188, in run
          self.run_command('build')
        File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-kddajcat/dm-tree_b4c24d53c3804d088de23bf53e53c2cb/setup.py", line 70, in run
          self._check_build_environment()
        File "/tmp/pip-install-kddajcat/dm-tree_b4c24d53c3804d088de23bf53e53c2cb/setup.py", line 82, in _check_build_environment
          ) from e
      RuntimeError: CMake must be installed to build the following extensions: _tree
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dm-tree
  Running setup.py clean for dm-tree
Failed to build dm-tree
Installing collected packages: dm-tree
  Running setup.py install for dm-tree ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for dm-tree did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-3.7
      creating build/lib.linux-aarch64-3.7/tree
      copying tree/tree_benchmark.py -> build/lib.linux-aarch64-3.7/tree
      copying tree/tree_test.py -> build/lib.linux-aarch64-3.7/tree
      copying tree/sequence.py -> build/lib.linux-aarch64-3.7/tree
      copying tree/__init__.py -> build/lib.linux-aarch64-3.7/tree
      running build_ext
      Traceback (most recent call last):
        File "/tmp/pip-install-kddajcat/dm-tree_b4c24d53c3804d088de23bf53e53c2cb/setup.py", line 77, in _check_build_environment
          subprocess.check_call(['cmake', '--version'])
        File "/usr/lib/python3.7/subprocess.py", line 342, in check_call
          retcode = call(*popenargs, **kwargs)
        File "/usr/lib/python3.7/subprocess.py", line 323, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
          restore_signals, start_new_session)
        File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-kddajcat/dm-tree_b4c24d53c3804d088de23bf53e53c2cb/setup.py", line 155, in <module>
          keywords='tree nest flatten',
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
          self.run_command('build')
        File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-kddajcat/dm-tree_b4c24d53c3804d088de23bf53e53c2cb/setup.py", line 70, in run
          self._check_build_environment()
        File "/tmp/pip-install-kddajcat/dm-tree_b4c24d53c3804d088de23bf53e53c2cb/setup.py", line 82, in _check_build_environment
          ) from e
      RuntimeError: CMake must be installed to build the following extensions: _tree
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dm-tree

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Chizkiyahu** [comment]
fixed at - #92
